# -*- coding: utf-8 -*-
"""P3D1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB_ExJHGGagS3KHdYGT90zrCSqWFot_C
"""

# Project 3 Draft 1 code
# Written by Cricket Bergner
# 03/10/26

# import libraries
import matplotlib.pyplot as plt
import numpy as np
import math
from prettytable import PrettyTable as pt

# integration functions

# RK2 Method
def RK2(N_initial, tmin, tmax, nts, deriv):

    # define initial variables
    N = np.zeros(nts + 1)
    N[0] = N_initial
    t = np.linspace(tmin, tmax, nts + 1)
    dt = t[1] - t[0]

    # loop the first and second substep
    for it in range(0, nts):
        N_half = N[it] + (dt / 2) * deriv(N[it], t[it])
        N[it+1] = N[it] + dt * deriv(N_half, t[it] + dt/2)

    return t, N

# Euler Method
def Euler_solver(N_initial, tmin, tmax, nts, deriv):

    # define initial variables
    N = np.zeros(nts + 1)
    N[0] = N_initial
    t = np.linspace(tmin, tmax, nts + 1)
    dt = t[1] - t[0]

    # loop
    for it in range(0,nts):
        N[it+1] = N[it] + dt * deriv(N[it], t[it])

    return t, N

# Scipy Method
def scipy_method(N_initial, tmin, tmax, nts, deriv):
    t = np.linspace(tmin, tmax, nts)
    N = odeint(deriv, N_initial, t)
    N = N.flatten()

    return t, N

# For a simple harmonic oscillator not at rest, what shape will it trace out in phase space?

# equation m (d^2y / dt^2) = -ky

# How does a SHM evolve with a linear damping term?

# How does the total mechanical energy (T+V) change over time with different solvers (see below) in these two cases?